project_id = "zwebxycbrfwtlmqwxwwe"

[functions.notify-manager]
verify_jwt = false

[functions.end-of-day]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.manage-user-access]
verify_jwt = true

[functions.upload-task-evidence]
verify_jwt = false
static_files = ["./functions/_shared/photo-decoder/magick.wasm.gz", "./functions/_shared/photo-decoder/NOTICE", "./functions/_shared/photo-decoder/LICENSE"]

[functions.cleanup-task-evidence]
verify_jwt = false
